#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
	rmdir /var/run/dbus || true

	rm -f /var/lib/dbus/machine-id
	rmdir /var/lib/dbus || true
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d dbus remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
